import { VideoLecture } from './types';

export const CURATED_VIDEO_LECTURES: VideoLecture[] = [
  // --- DSA Video Lectures ---
  {
    id: 'vid-dsa-en-01',
    title: 'Data Structures & Algorithms Masterclass - Trees & Graphs',
    channel: 'Abdul Bari',
    duration: '42:15',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=abdul+bari+algorithms+data+structures',
    topic: 'Binary Trees, AVL Trees & Graph Traversals',
    views: '3.4M views',
    subject: 'Data Structures & Algorithms',
    thumbnailColor: 'from-blue-600 via-indigo-700 to-indigo-900',
    recommendedFor: 'Foundational concepts and algorithmic proofs'
  },
  {
    id: 'vid-dsa-en-02',
    title: 'DSA Roadmap & Core Patterns (Blind 75 Explained)',
    channel: 'NeetCode',
    duration: '1:10:40',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=neetcode+dsa+roadmap+blind+75',
    topic: 'Two Pointers, Sliding Window, DP & Graphs',
    views: '1.9M views',
    subject: 'Data Structures & Algorithms',
    thumbnailColor: 'from-sky-600 via-blue-700 to-slate-900',
    recommendedFor: 'Placement coding round prep & LeetCode patterns'
  },
  {
    id: 'vid-dsa-hi-01',
    title: 'A2Z DSA Course in Hindi - Complete Binary Trees & Recursion',
    channel: 'take U forward (Striver)',
    duration: '58:30',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=take+u+forward+striver+dsa+hindi',
    topic: 'Trees, Recursion, Dynamic Programming',
    views: '2.6M views',
    subject: 'Data Structures & Algorithms',
    thumbnailColor: 'from-rose-600 via-purple-700 to-indigo-900',
    recommendedFor: 'Comprehensive semester & FAANG level problem solving in Hindi'
  },
  {
    id: 'vid-dsa-hi-02',
    title: 'Data Structures & Algorithms Full Course in Hindi (One-Shot)',
    channel: 'CodeWithHarry',
    duration: '1:45:00',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=codewithharry+dsa+in+hindi',
    topic: 'Arrays, Linked Lists, Stacks, Queues & Sorting',
    views: '4.8M views',
    subject: 'Data Structures & Algorithms',
    thumbnailColor: 'from-amber-600 via-orange-700 to-red-900',
    recommendedFor: 'Beginners starting from scratch with clear Hindi explanations'
  },
  {
    id: 'vid-dsa-te-01',
    title: 'Complete Data Structures in Telugu - Arrays, Stacks & Trees',
    channel: 'Vamsi Bhavani',
    duration: '1:12:00',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=vamsi+bhavani+data+structures+in+telugu',
    topic: 'Data Structures Foundations & Memory Models',
    views: '940K views',
    subject: 'Data Structures & Algorithms',
    thumbnailColor: 'from-emerald-600 via-teal-700 to-slate-900',
    recommendedFor: 'Telugu students preparing for university exams and interviews'
  },
  {
    id: 'vid-dsa-te-02',
    title: 'Binary Trees & Graph BFS/DFS Algorithms Explained in Telugu',
    channel: 'Telugu Web Guru',
    duration: '38:45',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=telugu+web+guru+data+structures',
    topic: 'Binary Search Trees & Traversal Algorithms',
    views: '380K views',
    subject: 'Data Structures & Algorithms',
    thumbnailColor: 'from-teal-600 via-emerald-800 to-zinc-900',
    recommendedFor: 'Fast revision before semester lab and theory exams in Telugu'
  },

  // --- M1 / Engineering Mathematics Video Lectures ---
  {
    id: 'vid-m1-en-01',
    title: 'Matrix Rank, Eigenvalues & Cayley-Hamilton Theorem Complete',
    channel: 'Dr. Gajendra Purohit',
    duration: '32:10',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=gajendra+purohit+matrices+eigenvalues+engineering+mathematics',
    topic: 'Rank of Matrix, System of Linear Equations, Cayley-Hamilton',
    views: '1.7M views',
    subject: 'Engineering Mathematics - I (M1)',
    thumbnailColor: 'from-indigo-600 via-blue-800 to-slate-900',
    recommendedFor: 'Clear derivations and exam shortcuts for scoring 100%'
  },
  {
    id: 'vid-m1-en-02',
    title: 'Differential Calculus & Taylor Series for Engineering Students',
    channel: 'Neso Academy',
    duration: '26:50',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=neso+academy+engineering+mathematics+calculus',
    topic: 'Taylor & Maclaurin Series, Partial Derivatives',
    views: '980K views',
    subject: 'Engineering Mathematics - I (M1)',
    thumbnailColor: 'from-blue-600 via-cyan-800 to-slate-900',
    recommendedFor: 'Step-by-step visual intuition of calculus fundamentals'
  },
  {
    id: 'vid-m1-hi-01',
    title: 'M1 Unit 1 Matrices & Diagonalization in Hindi (One Shot)',
    channel: 'Pradeep Giri Academy',
    duration: '45:20',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=pradeep+giri+academy+m1+matrices+hindi',
    topic: 'Matrices, Echelon Form, Diagonalization',
    views: '1.6M views',
    subject: 'Engineering Mathematics - I (M1)',
    thumbnailColor: 'from-red-600 via-orange-700 to-stone-900',
    recommendedFor: 'University semester preparation with solved model papers in Hindi'
  },
  {
    id: 'vid-m1-hi-02',
    title: 'Jacobians & Maxima-Minima of Two Variables Explained in Hindi',
    channel: 'Last Moment Tuitions',
    duration: '38:15',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=last+moment+tuitions+engineering+mathematics+m1+hindi',
    topic: 'Multivariable Calculus & High-Scoring Questions',
    views: '2.1M views',
    subject: 'Engineering Mathematics - I (M1)',
    thumbnailColor: 'from-rose-600 via-pink-800 to-neutral-900',
    recommendedFor: 'High-speed exam day revision notes and expected questions'
  },
  {
    id: 'vid-m1-te-01',
    title: 'Engineering Mathematics M1 Matrices & Eigenvalues in Telugu',
    channel: 'Harsha Tech Telugu',
    duration: '48:10',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=engineering+mathematics+m1+in+telugu+harsha+tech',
    topic: 'Rank of Matrix & Cayley Hamilton Theorem in Telugu',
    views: '710K views',
    subject: 'Engineering Mathematics - I (M1)',
    thumbnailColor: 'from-amber-600 via-yellow-700 to-stone-900',
    recommendedFor: 'JNTU / OU / VTU syllabus aligned tutorial in fluent Telugu'
  },
  {
    id: 'vid-m1-te-02',
    title: 'M1 Double & Triple Integrals Solved Problems in Telugu',
    channel: 'Telugu Engineering Tutorials',
    duration: '35:20',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=telugu+engineering+tutorials+m1+integrals',
    topic: 'Change of Order of Integration & Area Calculation',
    views: '450K views',
    subject: 'Engineering Mathematics - I (M1)',
    thumbnailColor: 'from-orange-600 via-amber-800 to-zinc-900',
    recommendedFor: 'Telugu medium engineering students mastering calculus problems'
  },

  // --- BEE / Basic Electrical Engineering Video Lectures ---
  {
    id: 'vid-bee-en-01',
    title: 'Mesh & Nodal Analysis (KCL / KVL) Complete Solved Walkthrough',
    channel: 'Neso Academy',
    duration: '34:20',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=neso+academy+basic+electrical+engineering+mesh+nodal',
    topic: 'Circuit Theory, Kirchhoff\'s Laws, Independent Sources',
    views: '3.1M views',
    subject: 'Basic Electrical Engineering (BEE)',
    thumbnailColor: 'from-blue-600 via-indigo-800 to-slate-900',
    recommendedFor: 'Zero-confusion step by step circuit analysis'
  },
  {
    id: 'vid-bee-en-02',
    title: 'Three Phase Circuits Star & Delta Connection Derivations',
    channel: 'Gate Smashers',
    duration: '22:15',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=gate+smashers+basic+electrical+star+delta',
    topic: 'Star vs Delta Relationship, Phasor Diagrams',
    views: '1.6M views',
    subject: 'Basic Electrical Engineering (BEE)',
    thumbnailColor: 'from-violet-600 via-purple-800 to-neutral-900',
    recommendedFor: 'Exam derivations and 10-mark theory questions'
  },
  {
    id: 'vid-bee-hi-01',
    title: 'Basic Electrical Engineering (BEE) Full Syllabus Revision in Hindi',
    channel: 'Engineers Ki Pathshala',
    duration: '46:30',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=engineers+ki+pathshala+basic+electrical+hindi',
    topic: 'Transformers, DC Machines & AC Fundamentals in Hindi',
    views: '880K views',
    subject: 'Basic Electrical Engineering (BEE)',
    thumbnailColor: 'from-amber-600 via-rose-700 to-stone-900',
    recommendedFor: 'Full concept clarity with Hindi commentary and diagrams'
  },
  {
    id: 'vid-bee-hi-02',
    title: 'BEE in One Night! Transformer Working & Equivalent Circuit Hindi',
    channel: 'Last Moment Tuitions',
    duration: '1:18:00',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=last+moment+tuitions+bee+basic+electrical+hindi',
    topic: 'Single Phase Transformers, Efficiency & Losses',
    views: '3.9M views',
    subject: 'Basic Electrical Engineering (BEE)',
    thumbnailColor: 'from-red-600 via-orange-800 to-stone-900',
    recommendedFor: 'Last-minute mid-term and semester exam revision'
  },
  {
    id: 'vid-bee-te-01',
    title: 'Basic Electrical Engineering KCL & KVL Node Analysis in Telugu',
    channel: 'Telugu Tech Tutorials',
    duration: '31:40',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=basic+electrical+engineering+in+telugu+kcl+kvl',
    topic: 'DC Circuits, Node Voltage Method & Supermesh in Telugu',
    views: '410K views',
    subject: 'Basic Electrical Engineering (BEE)',
    thumbnailColor: 'from-yellow-600 via-amber-800 to-zinc-900',
    recommendedFor: 'Telugu engineering students tackling electrical circuits easily'
  },
  {
    id: 'vid-bee-te-02',
    title: 'Single Phase AC Circuits Phasor Diagrams & Power Factor in Telugu',
    channel: 'Engineering in Telugu',
    duration: '27:15',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=engineering+in+telugu+basic+electrical+transformers',
    topic: 'Transformers & AC Power in Telugu',
    views: '320K views',
    subject: 'Basic Electrical Engineering (BEE)',
    thumbnailColor: 'from-emerald-700 via-teal-800 to-slate-900',
    recommendedFor: 'Concept explanation and previous year solved questions in Telugu'
  },

  // --- Python / First Year Video Lectures ---
  {
    id: 'vid-py-en-01',
    title: 'Python Programming Full Course for Engineering Students',
    channel: 'freeCodeCamp.org',
    duration: '4:26:00',
    language: 'English',
    url: 'https://www.youtube.com/results?search_query=freecodecamp+python+programming+full+course',
    topic: 'Syntax, Data Structures, OOP & Standard Libraries',
    views: '43M views',
    subject: 'Programming for Problem Solving (Python)',
    thumbnailColor: 'from-blue-700 via-indigo-900 to-slate-950',
    recommendedFor: 'Complete hands-on programming from hello world to projects'
  },
  {
    id: 'vid-py-hi-01',
    title: 'Complete Python Course for College Students in Hindi',
    channel: 'Apna College',
    duration: '2:15:00',
    language: 'Hindi',
    url: 'https://www.youtube.com/results?search_query=apna+college+python+course+in+hindi',
    topic: 'Basics, Loops, Functions, File I/O, OOP in Hindi',
    views: '6.1M views',
    subject: 'Programming for Problem Solving (Python)',
    thumbnailColor: 'from-purple-600 via-pink-700 to-rose-950',
    recommendedFor: 'College lab exam preparations & Python basics'
  },
  {
    id: 'vid-py-te-01',
    title: 'Python Programming Full Tutorial in Telugu for Beginners',
    channel: 'Telugu Coding Community',
    duration: '1:35:00',
    language: 'Telugu',
    url: 'https://www.youtube.com/results?search_query=python+programming+in+telugu+full+course',
    topic: 'Python Basics, Lists, Dictionaries & Functions in Telugu',
    views: '620K views',
    subject: 'Programming for Problem Solving (Python)',
    thumbnailColor: 'from-amber-600 via-yellow-700 to-stone-900',
    recommendedFor: 'Telugu students learning coding from scratch'
  }
];
